# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk: oraclejdk9
# используем режим обычного пользователя для сборки проекта.
sudo: true

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - suminfx@mail.ru
    on_success: never # default: change
    on_failure: always # default: always